##### Title: Exercice 5.2
##### Author: Jerock Kalala
##### Date: January 27th 2023
##### Modified By: --
##### Using Natural Language Processing (NLP)


 Using the file, twitter_sample.csv file, which can be found in the "data" directory in the Week 5 GitHub repository:

In [130]:
import pandas as pd
import numpy as np
import nltk
import re
import matplotlib.pyplot as plt
%matplotlib inline
import nltk
from nltk.stem.snowball import SnowballStemmer
from nltk.corpus import stopwords
import spacy
from datetime import date
nlp = spacy.load("en_core_web_sm")

corpus = pd.read_csv("E:\\Bellevue\\Winter_2022\\DSC 360 Data Mining Text Analytics an\Week_5\\twitter_sample.csv")
corpus[:5]

Tweet Id                                          Tweet URL  \
0  "1167429261210218497"  https://twitter.com/animalhealthEU/status/1167...   
1  "1167375334670557185"  https://twitter.com/PennyBrohnUK/status/116737...   
2  "1167237977615097861"  https://twitter.com/lordbyronaf/status/1167237...   
3  "1167236897078480898"  https://twitter.com/CountessDavis/status/11672...   
4  "1167228378191204353"  https://twitter.com/Local12/status/11672283781...   

  Tweet Posted Time (UTC)                                      Tweet Content  \
0    30 Aug 2019 13:30:00  Pets change our lives &amp; become a part of o...   
1    30 Aug 2019 09:55:43  Another spot of our #morethanmedicine bus in #...   
2    30 Aug 2019 00:49:54  What a great team ⁦@HealthSourceOH⁩ ⁦@Local12⁩...   
3    30 Aug 2019 00:45:37  What a great team ⁦@HealthSourceOH⁩ ⁦@Local12⁩...   
4    30 Aug 2019 00:11:46  What a great team ⁦@HealthSourceOH⁩ ⁦@Local12⁩...   

  Tweet Type                Client  Retweets Received  Likes Received  \
0      Tweet  Twitter Ads Composer                  0               4   
1      Tweet       Twitter Web App                  0               5   
2    ReTweet   Twitter for Android                  0               0   
3    ReTweet   Twitter for Android                  0               0   
4    ReTweet             TweetDeck                  0               0   

   Tweet Location Tweet Language  ...                 Name        Username  \
0        Brussels        English  ...   AnimalhealthEurope  animalhealthEU   
1   Pill, Bristol        English  ...       Penny Brohn UK    PennyBrohnUK   
2       Ohio, USA        English  ...         Lord ByronAF     lordbyronaf   
3             NaN        English  ...  Lisa Countess davis   CountessDavis   
4  Cincinnati, OH        English  ...     Local 12/WKRC-TV         Local12   

                                            User Bio Verified or Non-Verified  \
0  AnimalhealthEurope represents manufacturers of...             Non-Verified   
1  We help people live well with the impact of ca...             Non-Verified   
2  It's easier to be who you are, than it is to b...             Non-Verified   
3  I am named after @ElvisPresley daughter Lisa M...             Non-Verified   
4  Local 12 is #Cincinnati's trusted source for b...                 Verified   

                          Profile URL Protected or Non-protected  \
0  https://twitter.com/animalhealthEU              Non-Protected   
1    https://twitter.com/PennyBrohnUK              Non-Protected   
2     https://twitter.com/lordbyronaf              Non-Protected   
3   https://twitter.com/CountessDavis              Non-Protected   
4         https://twitter.com/Local12              Non-Protected   

  User Followers  User Following  User Account Creation Date Impressions  
0           3697             542        17 Dec 2012 09:14:15        7394  
1           3227            1571        15 Sep 2010 09:44:02        6454  
2           7808            8617        25 Jul 2012 15:43:47           0  
3            291              81        26 Jan 2017 18:21:42           0  
4         198675             651        02 Sep 2008 20:09:44           0  

[5 rows x 21 columns]

In [131]:
wpt = nltk.WordPunctTokenizer()
stop_words = nltk.corpus.stopwords.words('English')

def normalize_document(doc):
    # lowercase and remove special characters\whitespace
    doc = re.sub(r'[^a-zA-Z\s]', '', doc, re.I|re.A)
    doc = doc.lower()
    doc = doc.strip()
    #tokenize document
    tokens = wpt.tokenize(doc)
    # filter stopwords out of document
    filtered_tokens = [token for token in tokens if token not in stop_words]
    # re-create document from filtered tokens
    doc = ' '.join(filtered_tokens)
    doc = re.sub('\n',' ',doc)
    return doc

normalize_corpus = np.vectorize(normalize_document)

def clean_tweets(doc):
    doc = doc.str.replace('[^\w\s]', '', regex=True)
    doc = doc.apply(lambda x: ' '.join([word for word in x.split() if word not in stop_words]))
    return doc

1. Clean the “Tweet Content” column by removing non-text data and stop words.

In [132]:
#corpus['Clean Tweets'] = normalize_corpus(corpus['Tweet Content'])
corpus['Tweet Content'] = normalize_corpus(corpus['Tweet Content'])
corpus.head()

Tweet Id                                          Tweet URL  \
0  "1167429261210218497"  https://twitter.com/animalhealthEU/status/1167...   
1  "1167375334670557185"  https://twitter.com/PennyBrohnUK/status/116737...   
2  "1167237977615097861"  https://twitter.com/lordbyronaf/status/1167237...   
3  "1167236897078480898"  https://twitter.com/CountessDavis/status/11672...   
4  "1167228378191204353"  https://twitter.com/Local12/status/11672283781...   

  Tweet Posted Time (UTC)                                      Tweet Content  \
0    30 Aug 2019 13:30:00  pets change lives amp become part families tha...   
1    30 Aug 2019 09:55:43  another spot morethanmedicine bus bristol week...   
2    30 Aug 2019 00:49:54  great team healthsourceoh local morethanmedici...   
3    30 Aug 2019 00:45:37  great team healthsourceoh local morethanmedici...   
4    30 Aug 2019 00:11:46  great team healthsourceoh local morethanmedici...   

  Tweet Type                Client  Retweets Received  Likes Received  \
0      Tweet  Twitter Ads Composer                  0               4   
1      Tweet       Twitter Web App                  0               5   
2    ReTweet   Twitter for Android                  0               0   
3    ReTweet   Twitter for Android                  0               0   
4    ReTweet             TweetDeck                  0               0   

   Tweet Location Tweet Language  ...                 Name        Username  \
0        Brussels        English  ...   AnimalhealthEurope  animalhealthEU   
1   Pill, Bristol        English  ...       Penny Brohn UK    PennyBrohnUK   
2       Ohio, USA        English  ...         Lord ByronAF     lordbyronaf   
3             NaN        English  ...  Lisa Countess davis   CountessDavis   
4  Cincinnati, OH        English  ...     Local 12/WKRC-TV         Local12   

                                            User Bio Verified or Non-Verified  \
0  AnimalhealthEurope represents manufacturers of...             Non-Verified   
1  We help people live well with the impact of ca...             Non-Verified   
2  It's easier to be who you are, than it is to b...             Non-Verified   
3  I am named after @ElvisPresley daughter Lisa M...             Non-Verified   
4  Local 12 is #Cincinnati's trusted source for b...                 Verified   

                          Profile URL Protected or Non-protected  \
0  https://twitter.com/animalhealthEU              Non-Protected   
1    https://twitter.com/PennyBrohnUK              Non-Protected   
2     https://twitter.com/lordbyronaf              Non-Protected   
3   https://twitter.com/CountessDavis              Non-Protected   
4         https://twitter.com/Local12              Non-Protected   

  User Followers  User Following  User Account Creation Date Impressions  
0           3697             542        17 Dec 2012 09:14:15        7394  
1           3227            1571        15 Sep 2010 09:44:02        6454  
2           7808            8617        25 Jul 2012 15:43:47           0  
3            291              81        26 Jan 2017 18:21:42           0  
4         198675             651        02 Sep 2008 20:09:44           0  

[5 rows x 21 columns]

2. Filtering only tweets (not re-tweets) use your class from part one of this exercise to build BOW and TF-IDF Vectorizer representations of the text; print your results. Don't over-think this, leverage what the author does in the text.

In [133]:
#BOW
print('Bag of Words Model')
# starting on page 208
from sklearn.feature_extraction.text import CountVectorizer
# get bag of words features in sparse format
cv = CountVectorizer(min_df=0., max_df=1.)
cv_matrix = cv.fit_transform(corpus['Tweet Type'])
# view non-zero feature positions in the sparse matrix
print(cv_matrix, '\n')

# view dense representation
# warning - might give a memory error if the data is too big
cv_matrix = cv_matrix.toarray()
print(cv_matrix, '\n')

# get all unique words in the corpus
vocab = cv.get_feature_names_out()
#show document feature vectors
cv_df = pd.DataFrame(cv_matrix, columns=vocab)
print(cv_df, '\n')

# you can set the n-gram range to 1,2 to get unigrams as well as bigrams
bv = CountVectorizer(ngram_range=(2,2))
bv_matrix = bv.fit_transform(corpus['Tweet Type'])
bv_matrix = bv_matrix.toarray()
vocab = bv.get_feature_names_out()
bv_df = pd.DataFrame(bv_matrix, columns=vocab)
print(bv_df, '\n')

Bag of Words Model
  (0, 2)	1
  (1, 2)	1
  (2, 1)	1
  (3, 1)	1
  (4, 1)	1
  (5, 2)	1
  (6, 1)	1
  (7, 1)	1
  (8, 1)	1
  (9, 1)	1
  (10, 1)	1
  (11, 2)	1
  (12, 2)	1
  (13, 1)	1
  (14, 0)	1
  (15, 1)	1
  (16, 1)	1
  (17, 2)	1
  (18, 2)	1
  (19, 1)	1
  (20, 1)	1
  (21, 2)	1
  (22, 1)	1
  (23, 2)	1
  (24, 1)	1
  :	:
  (361, 2)	1
  (362, 1)	1
  (363, 2)	1
  (364, 2)	1
  (365, 1)	1
  (366, 2)	1
  (367, 1)	1
  (368, 1)	1
  (369, 1)	1
  (370, 1)	1
  (371, 0)	1
  (372, 1)	1
  (373, 1)	1
  (374, 1)	1
  (375, 1)	1
  (376, 1)	1
  (377, 1)	1
  (378, 2)	1
  (379, 1)	1
  (380, 2)	1
  (381, 1)	1
  (382, 2)	1
  (383, 1)	1
  (384, 1)	1
  (385, 2)	1 

[[0 0 1]
 [0 0 1]
 [0 1 0]
 ...
 [0 1 0]
 [0 1 0]
 [0 0 1]] 

     reply  retweet  tweet
0        0        0      1
1        0        0      1
2        0        1      0
3        0        1      0
4        0        1      0
..     ...      ...    ...
381      0        1      0
382      0        0      1
383      0        1      0
384      0        1      0

ValueError: empty vocabulary; perhaps the documents only contain stop words

In [134]:
#Tf-Idf Transformer
print('tfidf transformer:')
from sklearn.feature_extraction.text import TfidfTransformer
tt = TfidfTransformer(norm = 'l2', use_idf=True)
tt_matrix = tt.fit_transform(cv_matrix)
tt_matrix = tt_matrix.toarray()
vocab = cv.get_feature_names_out()
print(pd.DataFrame(np.round(tt_matrix, 2), columns=vocab), '\n')

tfidf transformer:
     reply  retweet  tweet
0      0.0      0.0    1.0
1      0.0      0.0    1.0
2      0.0      1.0    0.0
3      0.0      1.0    0.0
4      0.0      1.0    0.0
..     ...      ...    ...
381    0.0      1.0    0.0
382    0.0      0.0    1.0
383    0.0      1.0    0.0
384    0.0      1.0    0.0
385    0.0      0.0    1.0

[386 rows x 3 columns] 



3. Find one or more documents (each tweet is a document) that are similar to each other using Cosine Similarity; print your results. (NOTE: the lower the Cosine Similarity, the more likely the documents are similar.)

In [135]:
print('tfidf vectorizer:')
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(min_df=0., max_df=1., norm='l2', use_idf=True, smooth_idf=True)
tv_matrix = tv.fit_transform(corpus['Tweet Content'])
tv_matrix = tv_matrix.toarray()
# this part is not in the book - save the tv_matrix for use later on
import os
np.save('tv_matrix.npy', tv_matrix)

vocab = tv.get_feature_names_out()
print(pd.DataFrame(np.round(tv_matrix, 2), columns=vocab), '\n')

tfidf vectorizer:
     ability  academic  acep  acepnow  acoeprso  across  act  activity  \
0        0.0      0.00   0.0      0.0       0.0     0.0  0.0       0.0   
1        0.0      0.00   0.0      0.0       0.0     0.0  0.0       0.0   
2        0.0      0.00   0.0      0.0       0.0     0.0  0.0       0.0   
3        0.0      0.00   0.0      0.0       0.0     0.0  0.0       0.0   
4        0.0      0.00   0.0      0.0       0.0     0.0  0.0       0.0   
..       ...       ...   ...      ...       ...     ...  ...       ...   
381      0.0      0.00   0.0      0.0       0.0     0.0  0.0       0.0   
382      0.0      0.23   0.0      0.0       0.0     0.0  0.0       0.0   
383      0.0      0.00   0.0      0.0       0.0     0.0  0.0       0.0   
384      0.0      0.00   0.0      0.0       0.0     0.0  0.0       0.0   
385      0.0      0.00   0.0      0.0       0.0     0.0  0.0       0.0   

     address  advice  ...  yet  youll  young  youre  zoetis  zones  zoonosen  \
0        0.0 

In [136]:
# load the tv_matrix save in the last file
tv_matrix = np.load('tv_matrix.npy')

# Document Similarity - staring on page 221
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(tv_matrix)
similarity_df = pd.DataFrame(similarity_matrix)
print('Similarity matrix DF:\n', similarity_df, '\n')

Similarity matrix DF:
           0         1         2         3         4         5         6    \
0    1.000000  0.002240  0.003851  0.003851  0.003851  0.003851  0.002302   
1    0.002240  1.000000  0.004446  0.004446  0.004446  0.004446  0.002658   
2    0.003851  0.004446  1.000000  1.000000  1.000000  1.000000  0.004569   
3    0.003851  0.004446  1.000000  1.000000  1.000000  1.000000  0.004569   
4    0.003851  0.004446  1.000000  1.000000  1.000000  1.000000  0.004569   
..        ...       ...       ...       ...       ...       ...       ...   
381  0.090952  0.003131  0.005382  0.005382  0.005382  0.005382  0.003217   
382  0.001977  0.002283  0.076390  0.076390  0.076390  0.076390  0.087237   
383  0.090952  0.003131  0.005382  0.005382  0.005382  0.005382  0.003217   
384  0.090952  0.003131  0.005382  0.005382  0.005382  0.005382  0.003217   
385  0.090952  0.003131  0.005382  0.005382  0.005382  0.005382  0.003217   

          7         8         9    ...       376    

In [137]:
from collections import Counter
from math  import sqrt

def word2vec(word):
    # Count the number of characters in each word.
    count_characters = Counter(word)
    # Gets the set of characters and calculates the "length" of the vector.
    set_characters = set(count_characters)
    length = sqrt(sum(c*c for c in count_characters.values()))
    return count_characters, set_characters, length, word

In [138]:
def cosine_similarity(vector1, vector2, ndigits):

    # Get the common characters between the two character sets
    common_characters = vector1[1].intersection(vector2[1])
    # Sum of the product of each intersection character.
    product_summation = sum(vector1[0][character] * vector2[0]                  [character] for character in common_characters)
    # Gets the length of each vector from the word2vec output.
    length = vector1[2] * vector2[2]
    # Calculates cosine similarity and rounds the value to ndigits decimal places.
    if length == 0:
        # Set value to 0 if word is empty.
        similarity = 0
    else:
        similarity = round(product_summation/length, ndigits)
    return similarity

In [139]:
ndigits = (len(corpus['Tweet Content']))
similarity_threshold = 0

In [146]:
def find_similar(full_names_list, similarity_threshold, ndigits):
    # Initiate an empty list to store results.
    results_list = []
    # Apply word2vec function to each name and store them in a list.
    vector_list = [word2vec(str(i)) for i in full_names_list]
    # Two loops to compare each vector with another vector only once.
    for i in range(len(vector_list)):
        # Get first vector
        vector1 = vector_list[i]
        for j in range(i+1, len(vector_list)):
            # Get the next vector
            vector2 = vector_list[j]
            # Calculate cosine similarity
            similarity_score = cosine_similarity(vector1, vector2, ndigits)
            # Append to results list if similarity score is between 1 and the threshold.
            # Note that scores of 1 can be ignored here if we want to exclude people with the same name.
            if 1 >= similarity_score >= similarity_threshold:
                results_list.append([vector1[3], vector2[3], similarity_score])
            else:
                pass
    # Convert list to dataframe.
    results_df = pd.DataFrame(results_list)
    if len(results_df) != 0:
        results_df.columns = ['Original_tweet', 'Compared_Tweet', 'Similarity_score']
    else:
    # Can add error here if there's no results to return if desired.
        pass
    return results_df

In [147]:
find_similar(corpus['Tweet Content'], similarity_threshold, ndigits)

Original_tweet  \
0      pets change lives amp become part families tha...   
1      pets change lives amp become part families tha...   
2      pets change lives amp become part families tha...   
3      pets change lives amp become part families tha...   
4      pets change lives amp become part families tha...   
...                                                  ...   
74176  great weekend rebellion back month tipsfornewd...   
74177  great weekend rebellion back month tipsfornewd...   
74178  morethanmedicine mean protecting animalhealth ...   
74179  morethanmedicine mean protecting animalhealth ...   
74180  morethanmedicine mean protecting animalhealth ...   

                                          Compared_Tweet  Similarity_score  
0      another spot morethanmedicine bus bristol week...          0.928081  
1      great team healthsourceoh local morethanmedici...          0.914231  
2      great team healthsourceoh local morethanmedici...          0.914231  
3      great team healthsourceoh local morethanmedici...          0.914231  
4      great team healthsourceoh local morethanmedici...          0.914231  
...                                                  ...               ...  
74176  morethanmedicine mean protecting animalhealth ...          0.933120  
74177  morethanmedicine mean protecting animalhealth ...          0.933120  
74178  morethanmedicine mean protecting animalhealth ...          1.000000  
74179  morethanmedicine mean protecting animalhealth ...          1.000000  
74180  morethanmedicine mean protecting animalhealth ...          1.000000  

[74181 rows x 3 columns]